-- 1. Create dedicated roles
CREATE ROLE IF NOT EXISTS DBT_DEV_ROLE;
CREATE ROLE IF NOT EXISTS DBT_PROD_ROLE;

-- 2. Grant warehouse usage
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_PROD_ROLE;

-- 3. Grant database + future schema privileges
GRANT USAGE, CREATE SCHEMA ON DATABASE SAP_DATAVAULT_DEMO TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON DATABASE SAP_DATAVAULT_DEMO TO ROLE DBT_PROD_ROLE;

-- 4. Grant full access to the dbt-specific schema(s)
GRANT ALL ON SCHEMA SAP_DATAVAULT_DEMO.PUBLIC TO ROLE DBT_DEV_ROLE;
GRANT ALL ON SCHEMA SAP_DATAVAULT_DEMO.PUBLIC TO ROLE DBT_PROD_ROLE;

-- 5. Grant read/write on current + future tables/views in those schemas
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SAP_DATAVAULT_DEMO.PUBLIC TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAP_DATAVAULT_DEMO.PUBLIC TO ROLE DBT_DEV_ROLE;

-- Same for prod schema (usually only SELECT + CREATE for prod)
GRANT ALL ON FUTURE TABLES IN SCHEMA SAP_DATAVAULT_DEMO.PUBLIC TO ROLE DBT_PROD_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA SAP_DATAVAULT_DEMO.PUBLIC TO ROLE DBT_PROD_ROLE;

-- 6. Assign the role to your user
GRANT ROLE DBT_DEV_ROLE TO USER SAPDEV1;
GRANT ROLE DBT_PROD_ROLE TO USER SAPDEV1;

-- 7. (Optional but recommended) Set default role
ALTER USER SAPDEV1 SET DEFAULT_ROLE = DBT_DEV_ROLE;
